//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.0.30319.1.
//
namespace CannedBytes.Midi.Device.Schema.Xml.Model1
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IsNullable = false)]
    public partial class deviceSchema : openAttrs
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("annotation", typeof(annotation), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("import", typeof(import), Order = 0)]
        public openAttrs[] Items;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataType", typeof(topLevelDataType), Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("recordType", typeof(topLevelRecordType), Order = 1)]
        public annotated[] Items1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string schema;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string version;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IsNullable = false)]
    public partial class annotation : openAttrs
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("appInfo", typeof(appInfo), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("documentation", typeof(documentation), Order = 0)]
        public object[] Items;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IsNullable = false)]
    public partial class appInfo
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlNode[] Any;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string source;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    public partial class recordExtensionType
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sequence", typeof(fieldSequence), Order = 0)]
        public fieldSequence sequence;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName @base;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    [System.Xml.Serialization.XmlRootAttribute("sequence", Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IsNullable = false)]
    public partial class fieldSequence
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("field", Order = 0)]
        public localField[] field;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    public partial class localField : field
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(localField))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    public abstract partial class field : annotated
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NCName")]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName type;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @fixed;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string repeats;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public uint width;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string property;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string address;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string size;

        public field()
        {
            this.repeats = "1";
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(facet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enumFacet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(intFacet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(uintFacet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(topLevelDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(localDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(field))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(localField))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(recordType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(topLevelRecordType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    public partial class annotated : openAttrs
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public annotation annotation;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(annotated))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(facet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enumFacet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(intFacet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(uintFacet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(topLevelDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(localDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(field))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(localField))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(recordType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(topLevelRecordType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    public partial class openAttrs
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(topLevelDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(localDataType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    public abstract partial class dataType : annotated
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extension", typeof(extension), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("restriction", typeof(restriction), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("union", typeof(union), Order = 0)]
        public annotated Item;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NCName")]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool @abstract;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int valueOffset;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(bitOrder.BigEndian)]
        public bitOrder bitOrder;

        public dataType()
        {
            this.@abstract = false;
            this.valueOffset = 0;
            this.bitOrder = bitOrder.BigEndian;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IsNullable = false)]
    public partial class extension : annotated
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("enumeration", typeof(enumFacet), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("fixed", typeof(facet), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("length", typeof(uintFacet), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("maximum", typeof(facet), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("minimum", typeof(facet), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public facet[] Items;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName[] baseTypes;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    [System.Xml.Serialization.XmlRootAttribute("enumeration", Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IsNullable = false)]
    public partial class enumFacet : facet
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enumFacet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(intFacet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(uintFacet))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    [System.Xml.Serialization.XmlRootAttribute("minimum", Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IsNullable = false)]
    public partial class facet : annotated
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    public partial class intFacet : facet
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    [System.Xml.Serialization.XmlRootAttribute("length", Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IsNullable = false)]
    public partial class uintFacet : facet
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {
        /// <remarks/>
        enumeration,

        /// <remarks/>
        @fixed,

        /// <remarks/>
        length,

        /// <remarks/>
        maximum,

        /// <remarks/>
        minimum,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IsNullable = false)]
    public partial class restriction : annotated
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("enumeration", typeof(enumFacet), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("fixed", typeof(facet), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("length", typeof(uintFacet), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("maximum", typeof(facet), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("minimum", typeof(facet), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public facet[] Items;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName @base;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IncludeInSchema = false)]
    public enum ItemsChoiceType1
    {
        /// <remarks/>
        enumeration,

        /// <remarks/>
        @fixed,

        /// <remarks/>
        length,

        /// <remarks/>
        maximum,

        /// <remarks/>
        minimum,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IsNullable = false)]
    public partial class union : annotated
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataType", Order = 0)]
        public localDataType[] dataType;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName[] memberTypes;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    public partial class localDataType : dataType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    public enum bitOrder
    {
        /// <remarks/>
        LittleEndian,

        /// <remarks/>
        BigEndian,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(topLevelRecordType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    public abstract partial class recordType : annotated
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extension", typeof(recordExtensionType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("restriction", typeof(recordRestrictionType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("sequence", typeof(fieldSequence), Order = 0)]
        public object Item;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NCName")]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public uint width;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool @abstract;

        public recordType()
        {
            this.@abstract = false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    public partial class recordRestrictionType
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sequence", typeof(fieldSequence), Order = 0)]
        public fieldSequence sequence;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName @base;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IsNullable = false)]
    public partial class documentation
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlNode[] Any;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string source;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IsNullable = false)]
    public partial class import : annotated
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string schema;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string assembly;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    [System.Xml.Serialization.XmlRootAttribute("dataType", Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IsNullable = false)]
    public partial class topLevelDataType : dataType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10")]
    [System.Xml.Serialization.XmlRootAttribute("recordType", Namespace = "http://schemas.cannedbytes.com/midi-device-schema/midi-device-schema/10", IsNullable = false)]
    public partial class topLevelRecordType : recordType
    {
    }
}